// One knob for deadline-friendly performance cuts.
// 0 = pretty, 1 = balanced (smooth + good-looking — the demo default),
// 2 = fast, 3 = emergency laptop/potato mode.
// Bump this UP if the demo machine chugs, DOWN (to 0) for screenshots/trailer.
export const PERFORMANCE_LEVEL = 2;

const PROFILES = [
  {
    name: 'pretty',
    antialias: true,
    pixelRatioCap: 1.5,
    shadows: true,
    softShadows: true,
    shadowMapSize: 1024,
    toneMapping: true,
    postFX: 'full',
    bloomResolutionScale: 0.5,
    particles: true,
    particleMax: 2400,
    particleScale: 1,
    particleUpdateEvery: 1,
    portalParticles: true,
    portalParticleChance: 0.4,
    portalLights: true,
    dynamicPointLights: true,
    renderDistance: 3,
    initialChunkBuildBudget: 49,
    maxChunkBuildsPerUpdate: 49,
    healUpdateInterval: 0,
    voxelMaxDepth: 5,
    crashTerrainMaxDepth: 6,
    terrainCastsShadow: true,
    modelCastShadows: true,
    modelReceiveShadows: true,
    propScale: 1,
    enemyScale: 1,
    enemyAiDistanceSq: 2500,
    enemyResleepDistanceSq: 6400, // engaged foes go back to sleep past this (sq) + 5s
    instanceProps: false,         // pretty mode keeps real GLB props
    preloadActors: true,          // warm enemy/boss GLBs behind the loading fade
    spawnAddsScale: 1,
    loadSkybox: true,
    loadPropModels: true,
    loadActorModels: true,
    loadWeaponModels: true,
    loadCrashShipModel: true,
    crashEnvMap: true,
    crashTerrainSize: 56,
    crashPropScale: 1,
    crashSmokeInterval: 0.05,
    minimapFps: 60,
    hudFps: 60,
    skySegments: [32, 16],
    portalDiscSegments: 48,
    portalRingSegments: 32,
    hubSegments: 48,
  },
  {
    name: 'balanced',
    antialias: false,
    pixelRatioCap: 1.15,
    shadows: true,
    softShadows: false,
    shadowMapSize: 512,
    toneMapping: true,
    postFX: 'vignette',
    bloomResolutionScale: 0.35,
    particles: true,
    particleMax: 1400,
    particleScale: 0.65,
    particleUpdateEvery: 1,
    portalParticles: true,
    portalParticleChance: 0.22,
    portalLights: true,
    dynamicPointLights: true,
    renderDistance: 1,
    initialChunkBuildBudget: 25,
    maxChunkBuildsPerUpdate: 3,
    healUpdateInterval: 0.04,
    voxelMaxDepth: 3,
    crashTerrainMaxDepth: 4,
    terrainCastsShadow: false,
    modelCastShadows: false,
    modelReceiveShadows: true,
    propScale: 0.85,
    enemyScale: 0.9,
    enemyAiDistanceSq: 1600,
    enemyResleepDistanceSq: 4900,
    instanceProps: true,
    preloadActors: false,
    spawnAddsScale: 0.75,
    loadSkybox: false,
    loadPropModels: false, // instanced placeholder props — skips the 16MB rock GLBs
    loadActorModels: false,
    loadWeaponModels: false,
    loadCrashShipModel: true,
    crashEnvMap: false,
    crashTerrainSize: 48,
    crashPropScale: 0.7,
    crashSmokeInterval: 0.08,
    minimapFps: 20,
    hudFps: 30,
    skySegments: [24, 12],
    portalDiscSegments: 32,
    portalRingSegments: 24,
    hubSegments: 36,
  },
  {
    name: 'fast',
    antialias: false,
    pixelRatioCap: 1,
    shadows: false,
    softShadows: false,
    shadowMapSize: 256,
    toneMapping: false,
    postFX: 'none',
    bloomResolutionScale: 0.25,
    particles: true,
    particleMax: 500,
    particleScale: 0.18,
    particleUpdateEvery: 3,
    portalParticles: false,
    portalParticleChance: 0,
    portalLights: false,
    dynamicPointLights: false,
    renderDistance: 1,
    initialChunkBuildBudget: 16,
    maxChunkBuildsPerUpdate: 2,
    healUpdateInterval: 0.08,
    voxelMaxDepth: 2,
    crashTerrainMaxDepth: 2,
    terrainCastsShadow: false,
    modelCastShadows: false,
    modelReceiveShadows: false,
    propScale: 0.5,
    enemyScale: 0.75,
    enemyAiDistanceSq: 1225,
    enemyResleepDistanceSq: 3600,
    instanceProps: true,
    preloadActors: false,
    spawnAddsScale: 0.5,
    loadSkybox: false,
    loadPropModels: false,
    loadActorModels: false,
    loadWeaponModels: false,
    loadCrashShipModel: false,
    crashEnvMap: false,
    crashTerrainSize: 40,
    crashPropScale: 0.4,
    crashSmokeInterval: 0.14,
    minimapFps: 12,
    hudFps: 20,
    skySegments: [16, 8],
    portalDiscSegments: 24,
    portalRingSegments: 16,
    hubSegments: 32,
  },
  {
    name: 'potato',
    antialias: false,
    pixelRatioCap: 0.75,
    shadows: false,
    softShadows: false,
    shadowMapSize: 128,
    toneMapping: false,
    postFX: 'none',
    bloomResolutionScale: 0.2,
    particles: false,
    particleMax: 1,
    particleScale: 0,
    particleUpdateEvery: 4,
    portalParticles: false,
    portalParticleChance: 0,
    portalLights: false,
    dynamicPointLights: false,
    renderDistance: 1,
    initialChunkBuildBudget: 9,
    maxChunkBuildsPerUpdate: 1,
    healUpdateInterval: 0.12,
    voxelMaxDepth: 1,
    crashTerrainMaxDepth: 1,
    terrainCastsShadow: false,
    modelCastShadows: false,
    modelReceiveShadows: false,
    propScale: 0.25,
    enemyScale: 0.55,
    enemyAiDistanceSq: 900,
    enemyResleepDistanceSq: 2500,
    instanceProps: true,
    preloadActors: false,
    spawnAddsScale: 0.35,
    loadSkybox: false,
    loadPropModels: false,
    loadActorModels: false,
    loadWeaponModels: false,
    loadCrashShipModel: false,
    crashEnvMap: false,
    crashTerrainSize: 32,
    crashPropScale: 0.2,
    crashSmokeInterval: 0.25,
    minimapFps: 8,
    hudFps: 12,
    skySegments: [12, 6],
    portalDiscSegments: 16,
    portalRingSegments: 12,
    hubSegments: 24,
  },
];

export const PERF = PROFILES[Math.max(0, Math.min(PERFORMANCE_LEVEL, PROFILES.length - 1))];

export function scaledCount(count, scale, min = 0) {
  return Math.max(min, Math.ceil(count * scale));
}

export function pixelRatio() {
  return Math.min(window.devicePixelRatio || 1, PERF.pixelRatioCap);
}
